### ISSUE TITLE
CIS 6.0.0 disable_udf

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#1023]
```
cookbook_file 'Install [disable-udf] cloud config' do
  path '/etc/cloud/cloud.cfg.d/99-disable-udf.cfg'
  source 'etc/cloud/cloud.cfg.d/99-disable-udf.cfg'
  mode '0644'
end
```

**Comment by CecileRobertMichon** [comment]
```
# Disable UDF after provisioning has completed
write_files:
-   path: /etc/modprobe.d/CIS_disable_udf.conf
    owner: root:root
    permissions: '0644'
    content: |
        # 1.1.1.7 Ensure mounting of udf filesystems is disabled (Scored)
        # UDF is required for Azure provisioning. It must be disabled *after* provisioning
        install udf /bin/true
```
