### ISSUE TITLE
External Custom YAML manifests are not being created at expected path

### ISSUE THREAD

**Issue by allantargino** [Azure/aks-engine#1366]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of aks-engine?**: master

---

**Kubernetes version**: n/a

**What happened**:

When using [external custom YAML manifests](https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#external-custom-yaml-scripts), like:
```yaml
"kubernetesConfig": {
    "schedulerConfig": {
            "data" : "<base64 encoded string of your k8s manifest YAML>"
        }
}
```
or from an addon:
```yaml
"kubernetesConfig": {
    "addons": [
        {
            "name": "kube-proxy-daemonset",
            "enabled" : true,
            "data" : <base64 encoded string of your k8s addon YAML>,
        }
    ]
}
```
The expected resource is not created at the expected location, consequently the resources are not being handled/create by addons-manager or kubelet static manifests.

**What you expected to happen**:
* Custom addons to be created at `/etc/kubernetes/addons`
* Custom kubernetes component to be created at `/etc/kubernetes/manifests`

**How to reproduce it** (as minimally and precisely as possible):
1. Get an addon or component manifest, modify it and get its base64 encoding:
```shell
cat parts/k8s/addons/kubernetesmasteraddons-pod-security-policy.yaml | base64 -w0
```
2. Replace the data in your cluster definition at:
```yaml
      "kubernetesConfig": {
        "enableRbac": true,
        "enablePodSecurityPolicy": true,
        "addons": [
          {
            "name": "pod-security-policy",
            "enabled": true,
            "data": "YXBpVmVyc2lvbjogZXh0ZW5zaW9ucy92MWJldGExCmtpbmQ6IFBvZFNlY3VyaXR5UG9saWN5Cm1ldGFkYXRhOgogIG5hbWU6IHByaXZpbGVnZWQKICBhbm5vdGF0aW9uczoKICAgIHNlY2NvbXAuc2VjdXJpdHkuYWxwaGEua3ViZXJuZXRlcy5pby9hbGxvd2VkUHJvZmlsZU5hbWVzOiAiKiIKICBsYWJlbHM6CiAgICBhZGRvbm1hbmFnZXIua3ViZXJuZXRlcy5pby9tb2RlOiBSZWNvbmNpbGUKc3BlYzoKICBwcml2aWxlZ2VkOiB0cnVlCiAgYWxsb3dQcml2aWxlZ2VFc2NhbGF0aW9uOiB0cnVlCiAgYWxsb3dlZENhcGFiaWxpdGllczoKICAtICIqIgogIHZvbHVtZXM6CiAgLSAiKiIKICBob3N0TmV0d29yazogdHJ1ZQogIGhvc3RQb3J0czoKICAtIG1pbjogMAogICAgbWF4OiA2NTUzNQogIGhvc3RJUEM6IHRydWUKICBob3N0UElEOiB0cnVlCiAgcnVuQXNVc2VyOgogICAgcnVsZTogUnVuQXNBbnkKICBzZUxpbnV4OgogICAgcnVsZTogUnVuQXNBbnkKICBzdXBwbGVtZW50YWxHcm91cHM6CiAgICBydWxlOiBSdW5Bc0FueQogIGZzR3JvdXA6CiAgICBydWxlOiBSdW5Bc0FueQotLS0KYXBpVmVyc2lvbjogZXh0ZW5zaW9ucy92MWJldGExCmtpbmQ6IFBvZFNlY3VyaXR5UG9saWN5Cm1ldGFkYXRhOgogIG5hbWU6IHJlc3RyaWN0ZWQKICBhbm5vdGF0aW9uczoKICAgIHNlY2NvbXAuc2VjdXJpdHkuYWxwaGEua3ViZXJuZXRlcy5pby9hbGxvd2VkUHJvZmlsZU5hbWVzOiBkb2NrZXIvZGVmYXVsdAogICAgYXBwYXJtb3Iuc2VjdXJpdHkuYmV0YS5rdWJlcm5ldGVzLmlvL2FsbG93ZWRQcm9maWxlTmFtZXM6IHJ1bnRpbWUvZGVmYXVsdAogICAgc2VjY29tcC5zZWN1cml0eS5hbHBoYS5rdWJlcm5ldGVzLmlvL2RlZmF1bHRQcm9maWxlTmFtZTogIGRvY2tlci9kZWZhdWx0CiAgICBhcHBhcm1vci5zZWN1cml0eS5iZXRhLmt1YmVybmV0ZXMuaW8vZGVmYXVsdFByb2ZpbGVOYW1lOiAgcnVudGltZS9kZWZhdWx0CiAgbGFiZWxzOgogICAgYWRkb25tYW5hZ2VyLmt1YmVybmV0ZXMuaW8vbW9kZTogUmVjb25jaWxlCnNwZWM6CiAgcHJpdmlsZWdlZDogdHJ1ZQogIGFsbG93UHJpdmlsZWdlRXNjYWxhdGlvbjogZmFsc2UKICByZXF1aXJlZERyb3BDYXBhYmlsaXRpZXM6CiAgICAtIEFMTAogIHZvbHVtZXM6CiAgICAtIGNvbmZpZ01hcAogICAgLSBwZXJzaXN0ZW50Vm9sdW1lQ2xhaW0KICBob3N0TmV0d29yazogZmFsc2UKICBob3N0SVBDOiBmYWxzZQogIGhvc3RQSUQ6IGZhbHNlCiAgcnVuQXNVc2VyOgogICAgcnVsZTogTXVzdFJ1bkFzTm9uUm9vdAogIHNlTGludXg6CiAgICBydWxlOiBSdW5Bc0FueQogIHN1cHBsZW1lbnRhbEdyb3VwczoKICAgIHJ1bGU6IE11c3RSdW5BcwogICAgcmFuZ2VzOgogICAgICAjIEZvcmJpZCBhZGRpbmcgdGhlIHJvb3QgZ3JvdXAuCiAgICAgIC0gbWluOiAxCiAgICAgICAgbWF4OiA2NTUzNQogIGZzR3JvdXA6CiAgICBydWxlOiBNdXN0UnVuQXMKICAgIHJhbmdlczoKICAgICAgIyBGb3JiaWQgYWRkaW5nIHRoZSByb290IGdyb3VwLgogICAgICAtIG1pbjogMQogICAgICAgIG1heDogNjU1MzUKICByZWFkT25seVJvb3RGaWxlc3lzdGVtOiBmYWxzZQotLS0KYXBpVmVyc2lvbjogcmJhYy5hdXRob3JpemF0aW9uLms4cy5pby92MQpraW5kOiBDbHVzdGVyUm9sZQptZXRhZGF0YToKICBuYW1lOiBwc3A6cHJpdmlsZWdlZAogIGxhYmVsczoKICAgIGFkZG9ubWFuYWdlci5rdWJlcm5ldGVzLmlvL21vZGU6IFJlY29uY2lsZQpydWxlczoKLSBhcGlHcm91cHM6IFsnZXh0ZW5zaW9ucyddCiAgcmVzb3VyY2VzOiBbJ3BvZHNlY3VyaXR5cG9saWNpZXMnXQogIHZlcmJzOiAgICAgWyd1c2UnXQogIHJlc291cmNlTmFtZXM6CiAgLSBwcml2aWxlZ2VkCi0tLQphcGlWZXJzaW9uOiByYmFjLmF1dGhvcml6YXRpb24uazhzLmlvL3YxCmtpbmQ6IENsdXN0ZXJSb2xlCm1ldGFkYXRhOgogIG5hbWU6IHBzcDpyZXN0cmljdGVkCiAgbGFiZWxzOgogICAgYWRkb25tYW5hZ2VyLmt1YmVybmV0ZXMuaW8vbW9kZTogUmVjb25jaWxlCnJ1bGVzOgotIGFwaUdyb3VwczogWydleHRlbnNpb25zJ10KICByZXNvdXJjZXM6IFsncG9kc2VjdXJpdHlwb2xpY2llcyddCiAgdmVyYnM6ICAgICBbJ3VzZSddCiAgcmVzb3VyY2VOYW1lczoKICAtIHJlc3RyaWN0ZWQKLS0tCmFwaVZlcnNpb246IHJiYWMuYXV0aG9yaXphdGlvbi5rOHMuaW8vdjEKa2luZDogQ2x1c3RlclJvbGVCaW5kaW5nCm1ldGFkYXRhOgogIG5hbWU6IGRlZmF1bHQ6cmVzdHJpY3RlZAogIGxhYmVsczoKICAgIGFkZG9ubWFuYWdlci5rdWJlcm5ldGVzLmlvL21vZGU6IFJlY29uY2lsZQpyb2xlUmVmOgogIGFwaUdyb3VwOiByYmFjLmF1dGhvcml6YXRpb24uazhzLmlvCiAga2luZDogQ2x1c3RlclJvbGUKICBuYW1lOiBwc3A6cmVzdHJpY3RlZApzdWJqZWN0czoKLSBraW5kOiBHcm91cAogIG5hbWU6IHN5c3RlbTphdXRoZW50aWNhdGVkCiAgYXBpR3JvdXA6IHJiYWMuYXV0aG9yaXphdGlvbi5rOHMuaW8KLS0tCmFwaVZlcnNpb246IHJiYWMuYXV0aG9yaXphdGlvbi5rOHMuaW8vdjEKa2luZDogUm9sZUJpbmRpbmcKbWV0YWRhdGE6CiAgbmFtZTogZGVmYXVsdDpwcml2aWxlZ2VkCiAgbmFtZXNwYWNlOiBrdWJlLXN5c3RlbQogIGxhYmVsczoKICAgIGFkZG9ubWFuYWdlci5rdWJlcm5ldGVzLmlvL21vZGU6IFJlY29uY2lsZQpyb2xlUmVmOgogIGFwaUdyb3VwOiByYmFjLmF1dGhvcml6YXRpb24uazhzLmlvCiAga2luZDogQ2x1c3RlclJvbGUKICBuYW1lOiBwc3A6cHJpdmlsZWdlZApzdWJqZWN0czoKLSBraW5kOiBHcm91cAogIG5hbWU6IHN5c3RlbTptYXN0ZXJzCiAgYXBpR3JvdXA6IHJiYWMuYXV0aG9yaXphdGlvbi5rOHMuaW8KLSBraW5kOiBHcm91cAogIG5hbWU6IHN5c3RlbTpzZXJ2aWNlYWNjb3VudHM6a3ViZS1zeXN0ZW0KICBhcGlHcm91cDogcmJhYy5hdXRob3JpemF0aW9uLms4cy5pbwo="
          }
        ]
      }
    }
```
3. Create it and ssh into the master node.
4. Check that instead of the file at `/etc/kubernetes/addons/pod-security-policy.yaml`, it is created by cloud-init at  `/pod-security-policy.yaml/etc/kubernetes/addons`:
```shell
$ stat /etc/kubernetes/addons/pod-security-policy.yaml
stat: cannot stat '/etc/kubernetes/addons/pod-security-policy.yaml': No such file or directory
$ stat /pod-security-policy.yaml/etc/kubernetes/addons
File: '/pod-security-policy.yaml/etc/kubernetes/addons'
  Size: 3095            Blocks: 8          IO Block: 4096   regular file
[...]
```
**Anything else we need to know**:
I strongly guess there is some function inverting path and file arguments 🔍
