### ISSUE TITLE
Temporary DNS issue after container started in Windows pod

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#189]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
0.27
---

**Kubernetes version**:
1.13.1

**What happened**:
The program can't send http request in first couple of seconds after container started, the error is "No such host is known", it will work after 1~2 seconds.

**What you expected to happen**:
The program can send http request immediately after container started

**How to reproduce it** (as minimally and precisely as possible):
.NET Core code:
```
while (true)
{
    Console.WriteLine(DateTime.UtcNow);
    try
    {
        var resp = new HttpClient().GetAsync("http://51.140.50.184:801/test.txt").Result;
        resp.EnsureSuccessStatusCode();
        Console.WriteLine(resp.StatusCode);

        var ip = Dns.GetHostEntry("www.google.com");
        Console.WriteLine(ip.HostName);
        break;
    }
    catch (Exception e)
    {
        Console.WriteLine(e.Message);
    }
    Thread.Sleep(TimeSpan.FromSeconds(1));
}
Thread.Sleep(Timeout.Infinite);
```

Dockerfile:
```
FROM microsoft/dotnet:2.1-runtime-nanoserver-1809
WORKDIR C:/approot
COPY . C:/approot/
ENTRYPOINT ["dotnet", "demo.dll"]
```

Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: demo
    image: my.azurecr.io/demo:v1
  imagePullSecrets:
    - name: registrycred
  nodeSelector:
    beta.kubernetes.io/os: windows
```

The output:
```
12/20/2018 9:27:30 AM
OK
No such host is known
12/20/2018 9:27:31 AM
OK
www.google.com
```

At the first second, it sent request by ip successfully, so the network was good, but the dns parse failed. At the next second, dns parse worked.

**Anything else we need to know**:
acs-engine 0.23/k8s 1.12/Windows 1803 works
aks-engine 0.27/k8s 1.13/Linux works
aks-engine 0.27/k8s 1.13/Windows 2019/.NET Framework does not work
aks-engine 0.27/k8s 1.13/Windows 2019/.NET Core does not work
