### ISSUE TITLE
Error deploying pods with GMSA - unknown field "windowsOptions"

### ISSUE THREAD

**Issue by jjburr** [Azure/aks-engine#2009]
followed each step on the doc [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/), however when creating a deployment with the gmsa account I get an error:

deployment.yaml": error validating data: ValidationError(Deployment.spec.template.spec.securityContext): unknown field "windowsOptions" in io.k8s.api.core.v1.PodSecurityContext; if you choose to ignore these errors, turn validation off with --validate=false

Problem:
Cant deploy pod with gmsa account in the deployment

Page to Update:
https://kubernetes.io/...

v1.14.6

deployment.yaml

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      securityContext:
        windowsOptions:
          gmsaCredentialSpecName: gmsa-web
      containers:
        - name: webapp
          image: somerepo.azurecr.io/someimage
          ports:
            - containerPort: 80
      dnsPolicy: "ClusterFirst"        
      nodeSelector:
        beta.kubernetes.io/os: windows
```
