### ISSUE TITLE
Temporary storage only shows 30GB even though underlying VM has 200GB.

### ISSUE THREAD

**Issue by sukhong** [Azure/aks-engine#2145]
I provisioned a cluster using aks-engine with Standard_D8_v3 VMs, which have 200GB temporary storage (https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general)

However, when I get nodes statistics, it shows that only 30GB is available:
```
kind: Node
  metadata:
    annotations:
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    labels:
      agentpool: agentpool
      beta.kubernetes.io/arch: amd64
      **beta.kubernetes.io/instance-type: Standard_D8_v3**
      beta.kubernetes.io/os: linux
      failure-domain.beta.kubernetes.io/region: eastus
      failure-domain.beta.kubernetes.io/zone: eastus-1
      kubernetes.azure.com/cluster: IAMKubernetesPRODEUS-a
      kubernetes.azure.com/role: agent
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: k8s-agentpool-12915089-vmss000000
      kubernetes.io/os: linux
      kubernetes.io/role: agent
      node-role.kubernetes.io/agent: ""
      storageprofile: managed
      storagetier: Standard_LRS
    name: k8s-agentpool-12915089-vmss000000
  status:
    allocatable:
      attachable-volumes-azure-disk: "16"
      cpu: "8"
      **ephemeral-storage: "28043041951"**
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 32150428Ki
      pods: "250"
    capacity:
      attachable-volumes-azure-disk: "16"
      cpu: "8"
      **ephemeral-storage: 30428648Ki**
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 32918428Ki
      pods: "250"
```
**Describe the bug**
Standard_D8_v3  VM has 200 GB Temp Storage, but we only see 30GB.

**Steps To Reproduce**
Create a cluster using aks-engine using any VM with > 30GB temporary storage. You will only see 30GB in Kubernetes.

**Expected behavior**
We must be able to fully utilize the full capacity of underlying VM's Temporary storage.

**AKS Engine version**
0.39.2

**Kubernetes version**
1.15.3

**Additional context**
