### ISSUE TITLE
Standard SKU Load Balancer is reporting 'null' for it's zone awareness

### ISSUE THREAD

**Issue by jsco2t** [Azure/aks-engine#3119]
**Describe the bug**
I have a cluster deployed with the following characteristics:

- Configured to have a `standard sku` loadbalancer
- Uses VMScaleSets for it's Node Pools
- The Node Pools are setup to support three availability zones
- I have 3 live nodes running (one in each availability zone). 
- A `k8s` service of type `loadbalancer` exposed.

Issue: The Azure LoadBalancer being created by by AKS is not reporting any zone awareness:

When requesting info about the `front end IP address` for the loadbalancer - I get:
```
"zones": null
```

**Steps To Reproduce**
1. Create a cluster matching the information provided above.
2. Expose a service in the cluster similar to the following:

```
kind: Service
apiVersion: v1
metadata:
  name: a-cool-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: cool-app
    app.kubernetes.io/part-of: some-service
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
```

3. Get the load balancer info using the `az cli`

```
az network lb frontend-ip list -g some-rg-created-by-aks --lb-name kubernetes-internal

az network lb frontend-ip show --lb-name kubernetes-internal --name ip-address-name-here --resource-group some-rg-created-by-aks --subscription subscription-id-here
```

**Expected behavior**

I have confirmed that the AKS cluster is running a VMScaleSet and that the scaleset is spreading nodes across three availability zones. AKS in addition confirms that's it's understanding of the cluster:

```
$ kubectl describe nodes | grep -e "Name:" -e "failure-domain.beta.kubernetes.io/zone"

Name:               aks-default-SOMETHING-vmss000000
                    failure-domain.beta.kubernetes.io/zone=eastus-1
Name:               aks-default-SOMETHING-vmss000001
                    failure-domain.beta.kubernetes.io/zone=eastus-2
Name:               aks-default-SOMETHING-vmss000002
                    failure-domain.beta.kubernetes.io/zone=eastus-3
```

I was expecting the standard LB created by AKS to report that it was zone aware given this configuration. Because it's not reporting any zone awareness - I can't confirm that the IP Address fronting `k8s`/`aks` is really operating with any sort of zone fault tolerance.

Some questions:
1. Is there a way to configure `AKS` so that the `load balancers` it creates are `zone aware`?
-or-
2. Is the IP Address _actually_ zone aware and it's just not reporting that?

**AKS Engine version**
aks-release-v0.47.0-1-aks

**Kubernetes version**
1.15.10
