### ISSUE TITLE
azurefile + Windows doesn't work w/ containerd

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3315]
Our E2E tests tell us:

```
$ kubectl describe pod iis-azurefile
Name:         iis-azurefile
Namespace:    default
Priority:     0
Node:         2217k8s01000001/10.240.0.127
Start Time:   Wed, 20 May 2020 22:04:27 +0000
Labels:       name=storage
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"name":"storage"},"name":"iis-azurefile","namespace":"default"},"sp...
              kubernetes.io/psp: privileged
Status:       Pending
IP:           10.240.0.138
IPs:
  IP:  10.240.0.138
Containers:
  iis-azurefile:
    Container ID:   
    Image:          mcr.microsoft.com/windows/servercore/iis:20191112-windowsservercore-ltsc2019
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mnt/azure from azurefilevol (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7f7qp (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  azurefilevol:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pvc-azurefile
    ReadOnly:   false
  default-token-7f7qp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-7f7qp
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=windows
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                      Message
  ----     ------     ----                   ----                      -------
  Normal   Scheduled  <unknown>              default-scheduler         Successfully assigned default/iis-azurefile to 2217k8s01000001
  Warning  Failed     34m                    kubelet, 2217k8s01000001  Error: failed to generate container "e028f7a09d62b848c1ef7f345e827319bdc2dd235e828035693ab48abe2a4a9e" spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed     34m                    kubelet, 2217k8s01000001  Error: failed to generate container "6ff087d226e975d34e98d8aa4bf0f58fdbc65fc75e7b52b1b7c47c6986abb767" spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed     33m                    kubelet, 2217k8s01000001  Error: failed to generate container "9a2a3acb98a7237637517d17740f5bc36ea9a12a40831b6340369f81756086fc" spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed     33m                    kubelet, 2217k8s01000001  Error: failed to generate container "0fd3e5cb62f18111be2f7ba25cb7b6af905a82962294ec33aeeede60e0483fa0" spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed     33m                    kubelet, 2217k8s01000001  Error: failed to generate container "32f9c5d4a42f464ab3bb37e29de5c368132437aedef0bdca323178b3facc368c" spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed     33m                    kubelet, 2217k8s01000001  Error: failed to generate container "7a332a4d833f28d42ebbc77e3edd2364a36abc17af350b328c49ea5d944e1908" spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed     32m                    kubelet, 2217k8s01000001  Error: failed to generate container "35a708bf98fb6ed6c2276b04dcd23781ac3a4fc6b6cf75eb2f6326754d88f15f" spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed     32m                    kubelet, 2217k8s01000001  Error: failed to generate container "0b08e075d0c3898be8cb03bbad43ad9a78eed37d527c6f5563d30f3cb8b83389" spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed     32m                    kubelet, 2217k8s01000001  Error: failed to generate container "e6e68dbcfa38aba7395799d577bbfb329072e16b3fa866d9af1be6420ac3ae54" spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed     31m (x3 over 32m)      kubelet, 2217k8s01000001  (combined from similar events): Error: failed to generate container "bd4006ed5a4074d8a5d86be68f157f9d37cfe9bae240a068dabf9df276abd838" spec: failed to resolve symlink "": The system cannot find the file specified.
  Normal   Pulled     3m53s (x139 over 34m)  kubelet, 2217k8s01000001  Container image "mcr.microsoft.com/windows/servercore/iis:20191112-windowsservercore-ltsc2019" already present on machine
```

The PVC is scheduled fine (which makes sense, as there's no CRI story there):

```
$ kubectl describe pvc pvc-azurefile
Name:          pvc-azurefile
Namespace:     default
StorageClass:  azurefile
Status:        Bound
Volume:        pvc-3d7d5419-353c-4dfc-bf82-c182995cb1cc
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"pvc-azurefile","namespace":"default"},"spec":{"acce...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-file
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    iis-azurefile
Events:
  Type    Reason                 Age   From                         Message
  ----    ------                 ----  ----                         -------
  Normal  ProvisioningSucceeded  35m   persistentvolume-controller  Successfully provisioned volume pvc-3d7d5419-353c-4dfc-bf82-c182995cb1cc using kubernetes.io/azure-file
```

**Comment by jackfrancis** [comment]
Do we know status on this? Should it be a priority?

**Comment by marosset** [comment]
We're trying to get logs for container platform team to take a look but are running into issues getting logs with builds of containerd instrumented with the necessary logging.

**Comment by jackfrancis** [comment]
Thanks for the update!

**Comment by andyzhangx** [comment]
We use `New-SmbGlobalMapping` to mount azure file on a local path first and the use container volume mapping, so it looks like contianerd on windows could not resolve dir which is created by `New-SmbGlobalMapping`:
```console
New-SmbGlobalMapping -LocalPath x: -RemotePath \\xiazhang.file.core.windows.net\k8stest -Credential $Credential
docker run -d -v x:\:c:\mnt --name aspnet microsoft/aspnet
```

How can I try containerd on Windows? is there a doc link? thanks.

**Comment by jackfrancis** [comment]
@andyzhangx you can use an api model that looks like this test cluster config:

https://github.com/Azure/aks-engine/blob/master/test/e2e/test_cluster_configs/containerd.json

**Comment by andyzhangx** [comment]
looks like it's not related to azure file, basic image(`e2eteam/busybox:1.29`, `mcr.microsoft.com/windows/servercore/iis:20191112-windowsservercore-ltsc2019`) could not run on containerd cluster:
```
Events:
  Type     Reason                  Age                From                 Message
  ----     ------                  ----               ----                 -------
  Warning  FailedScheduling        79s (x3 over 91s)  default-scheduler    0/3 nodes are available: 1 node(s) didn't match node selector, 2 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
  Normal   Scheduled               74s                default-scheduler    Successfully assigned default/busybox-0 to 1094k8s001
  Warning  FailedCreatePodSandBox  74s                kubelet, 1094k8s001  Failed to create pod sandbox: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing open //./pipe/containerd-containerd: The system cannot find the file specified."
  Normal   Pulled                  12s                kubelet, 1094k8s001  Container image "mcr.microsoft.com/windows/servercore/iis:20191112-windowsservercore-ltsc2019" already present on machine
  Warning  Failed                  9s                 kubelet, 1094k8s001  Error: transport is closing
```

- my statefulset config:
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  serviceName: busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
        - name: busybox-azuredisk
          image: mcr.microsoft.com/windows/servercore/iis:20191112-windowsservercore-ltsc2019
          command:
            - "powershell.exe"
            - "-Command"
            - "while (1) { Add-Content -Encoding Ascii C:\\tmp\\data.txt $(Get-Date -Format u); sleep 1 }"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox
```

 - my cluster setup config
```yaml
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.18.6",
      "kubernetesConfig": {
        "networkPlugin": "azure",
        "containerRuntime": "containerd",
        "windowsContainerdURL": "https://github.com/containerd/containerd/releases/download/v1.4.0/containerd-1.4.0-windows-amd64.tar.gz"
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "andy-win11863",
      "vmSize": "Standard_DS2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "windowspool",
        "count": 2,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows",
        "osDiskSizeGB": 128,
        "extensions": [
            {
                "name": "winrm"
            }
        ]
      }
    ],
    "windowsProfile": {
      "adminUsername": "azureuser",
      "adminPassword": "...",
      "enableCSIProxy": true,
      "sshEnabled": true,
      "windowsPublisher": "microsoft-aks",
      "windowsOffer": "aks-windows",
      "windowsSku": "2019-datacenter-core-smalldisk-containerd-2005",
      "imageVersion": "latest"
    },
```

cc @AbelHu @jsturtevant
