### ISSUE TITLE
Update csi-secrets-store addon's rolling update strategy

### ISSUE THREAD

**Issue by jadarsie** [Azure/aks-engine#4088]
**Describe the request**

To update the `csi-secrets-store` addon spec to speed up rolling updates. 

@aramase, is there a downside to this? I am thinking something like this:

```yaml
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 50%
```

**Explain why AKS Engine needs it**

Restarting `csi-secrets-store` addon pods takes between 30s to 1m. On large clusters, this slows down `aks-engine rotate-certs` total time by a lot as `maxUnavailable` is currently set to 1 (default).
