### ISSUE TITLE
DNS doesn't work on second pod on node

### ISSUE THREAD

**Issue by davidmatson** [Azure/aks-engine#414]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
v0.28.1
---

**Kubernetes version**:
1.13.1

**What happened**:
DNS client calls don't work on the second pod on a node.

**What you expected to happen**:
DNS clients work fine regardless of whether existing pods exist on the node.

**How to reproduce it** (as minimally and precisely as possible):
Dockerfile:
```
FROM mcr.microsoft.com/windows/servercore:1809_KB4471332
ENTRYPOINT ["powershell.exe", "Add-Type -AssemblyName System.ServiceProcess;$sc = New-Object System.ServiceProcess.ServiceController 'winrm';$sc.WaitForStatus('Running');nslookup www.microsoft.com; curl.exe 23.44.161.156; curl.exe www.microsoft.com"]
```

Run two instances on the same node. Example deployments for a single-node cluster:
Deployment1.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  labels:
    app: test1
spec:
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: test
        image: my.azurecr.io/test
        imagePullPolicy: Always
      imagePullSecrets:
      - name: test
```
Deployment2.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
  labels:
    app: test2
spec:
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - name: test
        image: my.azurecr.io/test
        imagePullPolicy: Always
      imagePullSecrets:
      - name: test
```

**Anything else we need to know**:
Due to #189, I added code to wait for container startup to complete before attempting outbound calls. Note that nslookup always works, and curl with an IP address always works, but curl with a DNS name fails unless the node is completely empty of other pods.

The same problem exists with .NET code like HttpWebRequest or Dns.GetHostEntry/GetHostByName
