### ISSUE TITLE
Unable to access k8s dashboard

### ISSUE THREAD

**Issue by MirzaSikander** [Azure/aks-engine#453]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of aks-engine?**:
 v0.29.1
---

**Kubernetes version**:
v1.10.12

**What happened**:

When trying to access k8s Web UI dashboard using `kubectl proxy`, you get ` Unauthorized (401)
Authentication failed. Please try again.` 

I already created the following cluster role binding
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
  labels:
    k8s-app: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
```
**What you expected to happen**:
Should be able to access the dashboard. It works on  `k8s v1.10.9` that was deployed using `aks-engine v0.27.0`

**How to reproduce it** (as minimally and precisely as possible):
1) Deploy a brand new cluster with all default settings.
2) Create the Cluster role binding specified above.
3) Run `kubectl proxy`
4) Try to access [http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview?namespace=default](http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview?namespace=default)

**Anything else we need to know**:
