### ISSUE TITLE
Azure files volume mount causing significant slowdown of network perfomance

### ISSUE THREAD

**Issue by artisticcheese** [Azure/aks-engine#4843]
**Describe the bug**

Azure files volume mount into Windows containers reduces network throughput X times

**Steps To Reproduce**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks
  template:
    metadata:
      labels:
        app: aks
    spec:
      containers:
        - name: aks
          image: artisticcheese/aks-servercore
          volumeMounts:
            - name: logs
              mountPath: "logs"
            - name: logs
              mountPath: "logs1"
            - name: logs
              mountPath: "logs2"
            - name: logs
              mountPath: "logs3"
            - name: logs
              mountPath: "logs4"
            - name: logs
              mountPath: "logs5"
        - name: aks-clean
          image: artisticcheese/aks-servercore
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - key: kubernetes.io/os
          operator: Equal
          value: windows
          effect: NoSchedule
      volumes:
        - name: logs
          azureFile:
            secretName: fileshare-secret
            shareName: logs
            readOnly: false

```
This deploys 2 containers, one with 6 volume mounts and another one without it. Shell into each of them and execute following, which is connecting to 1.1.1.1 via HTTP in parallel 100 times, 10 times in a row and outputs average time it took to do it

```powershell
pwsh -c {1..10 | foreach {(measure-command {1..100 | ForEach-Object -parallel { Invoke-Webrequest "http://1.1.1.1" -Method head | out-null}}) | select -property totalseconds} | measure-object -Property TotalSeconds -AllStats | select Average}
```

**Expected behavior**
You shall be seeing similar statistics from both containers since they run on the same hardware, using the same image and generally exact copy of each other. In practice container with volume mounts slows down proportional to number of volume mappings. (for 6 mappings it's 6x slower)

6x volume mappings
```powershell
PS C:\workdir>  1..10 | foreach {(measure-command {1..100 | ForEach-Object -parallel { Invoke-Webrequest "http://1.1.1.1" -Method head | out-null}}) | select -property totalseconds} | measure-object -Property TotalSeconds -AllStats | select Average

   Average
   -------
6.36266226

```
No volume mappings
```powershell
PS C:\workdir>  1..10 | foreach {(measure-command {1..100 | ForEach-Object -parallel { Invoke-Webrequest "http://1.1.1.1" -Method head | out-null}}) | select -property totalseconds} | measure-object -Property TotalSeconds -AllStats | select Average

   Average
   -------
0.98009577
```

**AKS Engine version**
1.20.9

**Kubernetes version**
1.20.9

**Additional context**
