### ISSUE TITLE
Ask for Help: Is able to set egress address ?

### ISSUE THREAD

**Issue by luna1230** [Azure/aks-engine#774]
**Is this a request for help?**:
_Yes_ 
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
_Issue_
**What version of aks-engine?**:
_aks-engine-v0.28.1_

**Kubernetes version**:
"v1.11.5"
**What happened**:
I'd like to use static egress ip , but now is using random ip
**What you expected to happen**:
use static egress ip 
**How to reproduce it** (as minimally and precisely as possible):
I'd like to use an static egress address , like the aks document
https://docs.microsoft.com/en-us/azure/aks/egress
I create a static public ip 139.217.234.34
give the group network contributor access
my svc.yaml like that : 
```
azureuser@k8s-master-19596946-0:~$ cat test.yaml
apiVersion: v1
kind: Service
metadata:
  name: azure-egress
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: aabb
spec:
  loadBalancerIP: 139.217.234.34
  type: LoadBalancer
  ports:
  - port: 80
```

But when I verify the egress
the egress ip is not my assigned , it's a 139.217.232.70 . a random ip, I guess

**Anything else we need to know**:
